site_name: WPC Technology Documentation for Guests

repo_name: jackveney/wpc-tech-docs-guests
repo_url: https://github.com/jackveney/wpc-tech-docs-guests
edit_uri: ""
extra_css:
  - 'css/extra.css'

site_description: A reference for the technology located in Mackey Hall instnded for guests using the system.
site_author: Jack Veney
theme:
  name: material
  custom_dir: material/
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/WPC_logo.png
  favicon: assets/WPC_logo.png
  icon:
    repo: fontawesome/brands/github
  language: en
  static_templates:
    - 404.html

markdown_extensions:
  - tables
  - pymdownx.keys
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

copyright: Copyright &copy; 2022 Jack Veney - Westminster Presbyterian Church Wooster, Ohio
plugins:
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
  - search:
      lang: en
  - redirects:
      redirect_maps:
        docs.md: documentation/index.md
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
  - with-pdf:
      #author: WHO
      #copyright: ANY TEXT
      #
      cover: true
      back_cover: true
      cover_title: Guest Documentation
      cover_subtitle: Westminster Presbyterian Church - Mackey Hall Technology
      cover_logo: assets/images/banner.png
      #custom_template_path: TEMPLATES PATH
      #
      toc_title: Table of Contents
      #heading_shift: false
      toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      exclude_pages:
          - 'about/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      #output_path: any-place/document.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true
#  - mkpdfs:
#      company: Westminster Presbyterian Church
#      author: Jack Veney
#      toc_title: Table of contents
#      output_path: pdf/documentation.pdf
#  - pdf-export:
#      verbose: true
#      media_type: print
#      enabled_if_env: ENABLE_PDF_EXPORT
#      combined: true

# Page tree
nav:
  - Home: index.md
  - About: about.md
  - Documentation:
    - Documentation: documentation/index.md
    - Video:
      - Lowering Projector Screen: documentation/video/lowering_screen.md
      - Raising Projector Screen: documentation/video/raising_screen.md
      - Turning Projector On: documentation/video/turning_projector_on.md
      - Turning Projector Off: documentation/video/turning_projector_off.md
      - Input Methods: documentation/video/inputs.md
    - Audio:
      - Turning Sound System On: documentation/audio/turning_sound_system_on.md
      - Connecting iPad to Sound System: documentation/audio/ipad_sound_system.md
      - Using Computer Audio: documentation/audio/computer_audio.md
      - Connecting and Using Microphones: documentation/audio/microphones.md
      - Turning Sound System Off: documentation/audio/turning_sound_system_off.md
#    - Computers:
#      - Mackey Hall Computers: documentation/turning_projector_on.md
#      - Personal Computer: documentation/turning_projector_on.md
#    - Troubleshooting:
#      - iPad Not Connecting to Sound System: documentation/turning_projector_on.md
#      - No Sound Output: documentation/turning_projector_on.md
#      - No Computer Audio Output: documentation/turning_projector_on.md
#      - No Video Output from Projector: documentation/turning_projector_on.md
  - PDF: pdf/document.pdf